"""baseline closet schema

Revision ID: 7ec4e74c47bb
Revises: 
Create Date: 2026-06-03 17:45:54.871754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
try:
    from pgvector.sqlalchemy import Vector  # noqa: F401 — available for vector columns
except ModuleNotFoundError:
    Vector = None  # type: ignore

# revision identifiers, used by Alembic.
revision: str = '7ec4e74c47bb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # pgvector must exist before any Vector(1536) column is created. init.sql
    # enables it on a fresh postgres-closet volume, but guard here so the
    # baseline also applies on a pre-existing DB or a managed Postgres.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('ai_chat_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('summary_through_msg_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_chat_sessions_created_at'), 'ai_chat_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_chat_sessions_user_id'), 'ai_chat_sessions', ['user_id'], unique=False)
    op.create_table('closet_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=100), nullable=True),
    sa.Column('fabric', sa.String(length=100), nullable=True),
    sa.Column('pattern', sa.String(length=100), nullable=True),
    sa.Column('season', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('occasion', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('eco_score', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('size', sa.String(length=20), nullable=True),
    sa.Column('section', sa.String(length=50), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('embedding', Vector(dim=1536), nullable=True),
    sa.Column('wear_count', sa.Integer(), nullable=False),
    sa.Column('last_worn', sa.Date(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('original_image_url', sa.Text(), nullable=True),
    sa.Column('processed_image_url', sa.Text(), nullable=True),
    sa.Column('background_removed', sa.Boolean(), nullable=False),
    sa.Column('background_removal_status', sa.String(length=20), nullable=True),
    sa.Column('analysis_source', sa.String(length=50), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('scan_batch_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_closet_items_category'), 'closet_items', ['category'], unique=False)
    op.create_index(op.f('ix_closet_items_created_at'), 'closet_items', ['created_at'], unique=False)
    op.create_index(op.f('ix_closet_items_scan_batch_id'), 'closet_items', ['scan_batch_id'], unique=False)
    op.create_index(op.f('ix_closet_items_section'), 'closet_items', ['section'], unique=False)
    op.create_index(op.f('ix_closet_items_user_id'), 'closet_items', ['user_id'], unique=False)
    op.create_table('daily_nudges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('nudge_date', sa.Date(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('nudge_type', sa.String(length=40), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dismissed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'nudge_date', name='uq_daily_nudges_user_date')
    )
    op.create_table('fashion_knowledge_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('season', sa.String(length=50), nullable=True),
    sa.Column('occasion', sa.String(length=100), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('embedding', Vector(dim=1536), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fashion_knowledge_documents_category'), 'fashion_knowledge_documents', ['category'], unique=False)
    op.create_index(op.f('ix_fashion_knowledge_documents_title'), 'fashion_knowledge_documents', ['title'], unique=False)
    op.create_table('outfit_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('occasion', sa.String(length=100), nullable=True),
    sa.Column('weather_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('selected_item_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('matching_score', sa.Integer(), nullable=True),
    sa.Column('recommendation_text', sa.Text(), nullable=True),
    sa.Column('improvement_tips', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('user_feedback', sa.Text(), nullable=True),
    sa.Column('was_saved', sa.Boolean(), nullable=False),
    sa.Column('was_worn', sa.Boolean(), nullable=False),
    sa.Column('embedding', Vector(dim=1536), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outfit_history_created_at'), 'outfit_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_outfit_history_occasion'), 'outfit_history', ['occasion'], unique=False)
    op.create_index(op.f('ix_outfit_history_user_id'), 'outfit_history', ['user_id'], unique=False)
    op.create_table('outfits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('occasion', sa.String(length=100), nullable=True),
    sa.Column('item_ids', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('style_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outfits_user_id'), 'outfits', ['user_id'], unique=False)
    op.create_table('purchase_gaps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('gap_type', sa.String(length=50), nullable=False),
    sa.Column('missing_category', sa.String(length=100), nullable=False),
    sa.Column('missing_color', sa.String(length=50), nullable=True),
    sa.Column('missing_season', sa.String(length=50), nullable=True),
    sa.Column('missing_occasion', sa.String(length=100), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('priority_score', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('source_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('suggested_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_gaps_created_at'), 'purchase_gaps', ['created_at'], unique=False)
    op.create_index(op.f('ix_purchase_gaps_gap_type'), 'purchase_gaps', ['gap_type'], unique=False)
    op.create_index(op.f('ix_purchase_gaps_resolved'), 'purchase_gaps', ['resolved'], unique=False)
    op.create_index(op.f('ix_purchase_gaps_user_id'), 'purchase_gaps', ['user_id'], unique=False)
    op.create_table('trips',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('destination', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('purpose', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('trip_style', sa.String(length=50), nullable=True),
    sa.Column('bag_size', sa.String(length=50), nullable=True),
    sa.Column('activities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_saved', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trips_destination'), 'trips', ['destination'], unique=False)
    op.create_index(op.f('ix_trips_user_id'), 'trips', ['user_id'], unique=False)
    op.create_table('user_style_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('gender', sa.String(length=32), nullable=True),
    sa.Column('custom_gender', sa.String(length=120), nullable=True),
    sa.Column('height_value', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('height_unit', sa.String(length=8), nullable=True),
    sa.Column('weight_value', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('weight_unit', sa.String(length=8), nullable=True),
    sa.Column('age_range', sa.String(length=32), nullable=True),
    sa.Column('skin_tone', sa.String(length=32), nullable=True),
    sa.Column('undertone', sa.String(length=16), nullable=True),
    sa.Column('body_types', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('custom_body_type', sa.String(length=200), nullable=True),
    sa.Column('fit_preferences', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('custom_fit_notes', sa.String(length=500), nullable=True),
    sa.Column('size_profile', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('custom_size_notes', sa.String(length=500), nullable=True),
    sa.Column('style_preferences', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('favorite_colors', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('avoided_colors', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('neutral_color_preference', sa.Boolean(), nullable=True),
    sa.Column('bold_color_preference', sa.Boolean(), nullable=True),
    sa.Column('occasion_preferences', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('climate_preferences', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.Column('onboarding_skipped', sa.Boolean(), nullable=False),
    sa.Column('style_summary', sa.Text(), nullable=True),
    sa.Column('styling_goals', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True),
    sa.Column('avoidances', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True),
    sa.Column('pattern_preferences', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True),
    sa.Column('style_archetype', sa.String(length=100), nullable=True),
    sa.Column('recommendation_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_stylist_context', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_style_profiles_user_id'), 'user_style_profiles', ['user_id'], unique=True)
    op.create_table('ai_chat_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('structured_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['ai_chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_chat_messages_created_at'), 'ai_chat_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_chat_messages_session_id'), 'ai_chat_messages', ['session_id'], unique=False)
    op.create_index(op.f('ix_ai_chat_messages_user_id'), 'ai_chat_messages', ['user_id'], unique=False)
    op.create_table('outfit_feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('outfit_id', sa.UUID(), nullable=True),
    sa.Column('closet_item_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('feedback_text', sa.Text(), nullable=True),
    sa.Column('occasion', sa.String(length=100), nullable=True),
    sa.Column('mood', sa.String(length=100), nullable=True),
    sa.Column('was_worn', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['outfit_id'], ['outfits.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outfit_feedback_created_at'), 'outfit_feedback', ['created_at'], unique=False)
    op.create_index(op.f('ix_outfit_feedback_occasion'), 'outfit_feedback', ['occasion'], unique=False)
    op.create_index(op.f('ix_outfit_feedback_outfit_id'), 'outfit_feedback', ['outfit_id'], unique=False)
    op.create_index(op.f('ix_outfit_feedback_user_id'), 'outfit_feedback', ['user_id'], unique=False)
    op.create_table('packing_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('take_from_your_closet', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('you_might_still_need', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('daily_plan', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('weather_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('activities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('day_plans_rich', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rewear_strategy', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('bag_capacity_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('packing_checklist', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('checklist_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_saved', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trip_id', 'user_id', name='uq_packing_plans_trip_user')
    )
    op.create_index(op.f('ix_packing_plans_trip_id'), 'packing_plans', ['trip_id'], unique=False)
    op.create_index(op.f('ix_packing_plans_user_id'), 'packing_plans', ['user_id'], unique=False)
    op.create_table('packing_memory',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=True),
    sa.Column('destination', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.String(length=10), nullable=True),
    sa.Column('end_date', sa.String(length=10), nullable=True),
    sa.Column('purpose', sa.String(length=50), nullable=True),
    sa.Column('weather_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('packed_item_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('missing_items', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('saved_plan_id', sa.UUID(), nullable=True),
    sa.Column('user_feedback', sa.Text(), nullable=True),
    sa.Column('embedding', Vector(dim=1536), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['saved_plan_id'], ['packing_plans.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_packing_memory_created_at'), 'packing_memory', ['created_at'], unique=False)
    op.create_index(op.f('ix_packing_memory_destination'), 'packing_memory', ['destination'], unique=False)
    op.create_index(op.f('ix_packing_memory_trip_id'), 'packing_memory', ['trip_id'], unique=False)
    op.create_index(op.f('ix_packing_memory_user_id'), 'packing_memory', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_packing_memory_user_id'), table_name='packing_memory')
    op.drop_index(op.f('ix_packing_memory_trip_id'), table_name='packing_memory')
    op.drop_index(op.f('ix_packing_memory_destination'), table_name='packing_memory')
    op.drop_index(op.f('ix_packing_memory_created_at'), table_name='packing_memory')
    op.drop_table('packing_memory')
    op.drop_index(op.f('ix_packing_plans_user_id'), table_name='packing_plans')
    op.drop_index(op.f('ix_packing_plans_trip_id'), table_name='packing_plans')
    op.drop_table('packing_plans')
    op.drop_index(op.f('ix_outfit_feedback_user_id'), table_name='outfit_feedback')
    op.drop_index(op.f('ix_outfit_feedback_outfit_id'), table_name='outfit_feedback')
    op.drop_index(op.f('ix_outfit_feedback_occasion'), table_name='outfit_feedback')
    op.drop_index(op.f('ix_outfit_feedback_created_at'), table_name='outfit_feedback')
    op.drop_table('outfit_feedback')
    op.drop_index(op.f('ix_ai_chat_messages_user_id'), table_name='ai_chat_messages')
    op.drop_index(op.f('ix_ai_chat_messages_session_id'), table_name='ai_chat_messages')
    op.drop_index(op.f('ix_ai_chat_messages_created_at'), table_name='ai_chat_messages')
    op.drop_table('ai_chat_messages')
    op.drop_index(op.f('ix_user_style_profiles_user_id'), table_name='user_style_profiles')
    op.drop_table('user_style_profiles')
    op.drop_index(op.f('ix_trips_user_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_destination'), table_name='trips')
    op.drop_table('trips')
    op.drop_index(op.f('ix_purchase_gaps_user_id'), table_name='purchase_gaps')
    op.drop_index(op.f('ix_purchase_gaps_resolved'), table_name='purchase_gaps')
    op.drop_index(op.f('ix_purchase_gaps_gap_type'), table_name='purchase_gaps')
    op.drop_index(op.f('ix_purchase_gaps_created_at'), table_name='purchase_gaps')
    op.drop_table('purchase_gaps')
    op.drop_index(op.f('ix_outfits_user_id'), table_name='outfits')
    op.drop_table('outfits')
    op.drop_index(op.f('ix_outfit_history_user_id'), table_name='outfit_history')
    op.drop_index(op.f('ix_outfit_history_occasion'), table_name='outfit_history')
    op.drop_index(op.f('ix_outfit_history_created_at'), table_name='outfit_history')
    op.drop_table('outfit_history')
    op.drop_index(op.f('ix_fashion_knowledge_documents_title'), table_name='fashion_knowledge_documents')
    op.drop_index(op.f('ix_fashion_knowledge_documents_category'), table_name='fashion_knowledge_documents')
    op.drop_table('fashion_knowledge_documents')
    op.drop_table('daily_nudges')
    op.drop_index(op.f('ix_closet_items_user_id'), table_name='closet_items')
    op.drop_index(op.f('ix_closet_items_section'), table_name='closet_items')
    op.drop_index(op.f('ix_closet_items_scan_batch_id'), table_name='closet_items')
    op.drop_index(op.f('ix_closet_items_created_at'), table_name='closet_items')
    op.drop_index(op.f('ix_closet_items_category'), table_name='closet_items')
    op.drop_table('closet_items')
    op.drop_index(op.f('ix_ai_chat_sessions_user_id'), table_name='ai_chat_sessions')
    op.drop_index(op.f('ix_ai_chat_sessions_created_at'), table_name='ai_chat_sessions')
    op.drop_table('ai_chat_sessions')
    # ### end Alembic commands ###
